name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Install the dependencies
        run: npm i
      - name: Install vsce
        run: npm i -g @vscode/vsce
      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
